config/routes.rb
Rails.application.routes.draw do

  resources :projects, only: [:index, :show, :create, :destroy]

  resources :tasks, only: [:create, :destroy] do
    member do
      post :start, :stop, :finish
    end
  end

  root to: 'projects#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :task

  default_scope { order(:stop) }

  validates_presence_of :task

  def duration
    ((stop? ? stop : Time.now) - start).to_i
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :logs, through: :tasks

  validates_presence_of :name

  # Sum all time (in seconds) logged for a task
  def logged
    logs.map(&:duration).sum
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :logs, dependent: :destroy

  default_scope { order(:done, created_at: :desc) }

  validates_presence_of :name, :project

  # Task is considered "in work" if there is a task log without a stop time
  def in_work?
    !logs.empty? && !logs.first.stop?
  end

  def startable?
    !done? && !in_work?
  end

  def logged
    logs.map(&:duration).sum
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    @project = projects.first
  end

  def show
    @project = projects.find(params[:id])
  end

  def create
    @project = Project.create(name: params[:name])
    @projects = Project.all
  end

  def destroy
    @deleted = Project.find(params[:id]).destroy
    @project = projects.first
    render :show
  end 

  private

  def projects
    Project.includes(tasks: :logs)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @task = Project.find(params[:project_id]).tasks.create(name: params[:name])
  end

  def destroy
    @task = task
    @task.destroy
  end

  def finish
    @task = task
    @task.update(done: true)
    render :refresh
  end

  def start
    @task = task
    @log = Log.create(task: @task, start: Time.now)
    render :refresh
  end

  def stop
    @task = task
    @log = @task.logs.first.update(stop: Time.now)
    render :refresh
  end

  private

  def task
    Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper

  def format_logged(total)
    format("%02d:%02d:%02d", total/(60 *60), (total/60) % 60, total % 60)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype
html
  head
    title Trackapp
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = yield

app/views/logs/_log.html.slim
div[class="log#{' log-work' if !log.stop?}"]

  span.log-summary #{format_logged(log.duration)}
  
  span #{l(log.start, format: :long)}
  
  - if log.stop
    span &#8611; #{l(log.stop, format: :long)}

app/views/projects/_project.html.slim
= link_to project.name, project_path(project), {class: "project project-#{project.id}", remote: true}

app/views/projects/index.html.slim
ul.tabs
  li
    = form_tag( projects_path, method: :post, remote: true ) do
      = text_field_tag( :name, nil, placeholder: 'New project' )
  - @projects.each_with_index do |project, index|
    li[class="#{'active' if index == 0}#{' last' if index == @projects.size-1}"]
      = render project

.project-time= format_logged(@project.logged) if @project

= link_to 'delete project', projects_path(id: @project.id, format: 'js'), { class: 'project-delete', remote: true, method: :delete } if @project

.task-create
  = form_tag( tasks_path, method: :post, remote: true ) do
    = text_field_tag( :name, nil, placeholder: 'New task' )
    = hidden_field_tag( :project_id, "#{@projects.empty? ? 0 : @projects.first.id}" )

.taskpane
  = render @project.tasks if @project

app/views/tasks/_task.html.slim
div[class="task task-#{task.id} #{'task-in-work' if task.in_work?} #{'task-done' if task.done?}"]

  .time #{format_logged(task.logged)}

  - if task.in_work?
    = link_to 'stop', stop_task_path(task), { class: 'task-action action-stop', remote: true, method: :post }
  
  - if task.done?
    = link_to 'delete', task, { class: 'task-action action-delete', remote: true, method: :delete }

  - if task.startable?
    = link_to 'start', start_task_path(task), { class: 'task-action action-start', remote: true, method: :post }
    = link_to 'done', finish_task_path(task), { class: 'task-action action-done', remote: true, method: :post }
    
  .task-title
    - if task.in_work?
      span.icon &#9874;
    - elsif task.done?
      span.icon &#10003;
    - else
      span.icon &#9417;
    span #{task.name}
    - unless task.logs.empty?
      span.show-logs &#8609;
  
  div[class="task-logs logs-#{task.id}"]
    = render task.logs